apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Changes to testfake"
  name: deployment-test
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: fiware-orion
        image: fiware/orion
        ports:
            - containerPort: 1026
        resources:
              limits:
                  memory: {{.Values.limites.memoria}}
                  cpu: {{.Values.limites.cpu}}
              requests:
                  memory: {{.Values.peticiones.memoria}} 
                  cpu: {{.Values.peticiones.cpu}}
      - name: db-mongo
        image: mongo
        ports:
            - containerPort: 27017
        resources:
              limits:
                  memory: {{.Values.limites.memoria}}
                  cpu: {{.Values.limites.cpu}}
              requests:
                  memory: {{.Values.peticiones.memoria}} 
                  cpu: {{.Values.peticiones.cpu}}
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels: 
    app: front
spec:
  type: ClusterIP
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80