apiVersion: v1
kind: Pod
metadata:
  name: orion
spec:
  containers:
  - name: fiware-orion
    image: fiware/orion
    ports:
        - containerPort: 1026
    resources:
          limits:
              memory: {{.Values.limites.memoria}}
              cpu: {{.Values.limites.cpu}}
          requests:
              memory: {{.Values.peticiones.memoria}} 
              cpu: {{.Values.peticiones.cpu}}

---
apiVersion: v1
kind: Pod
metadata:
  name: mongo-db
spec:
  containers:
  - name: db-mongo
    image: mongo
    ports:
        - containerPort: 27017
    resources:
          limits:
              memory: {{.Values.limites.memoria}}
              cpu: {{.Values.limites.cpu}}
          requests:
              memory: {{.Values.peticiones.memoria}} 
              cpu: {{.Values.peticiones.cpu}}
